// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetOSAsync():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SignInAsync():Promise<void>;

export function UpdateSessionAsync():Promise<void>;
