// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOSAsync() {
  return window['go']['portalservice']['Service']['GetOSAsync']();
}

export function SetContext(arg1) {
  return window['go']['portalservice']['Service']['SetContext'](arg1);
}

export function SignInAsync() {
  return window['go']['portalservice']['Service']['SignInAsync']();
}

export function UpdateSessionAsync() {
  return window['go']['portalservice']['Service']['UpdateSessionAsync']();
}
