// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['gakusimservice']['Service']['SetContext'](arg1);
}

export function SimulateContestAsync() {
  return window['go']['gakusimservice']['Service']['SimulateContestAsync']();
}
