// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetAsync(arg1) {
  return window['go']['homeservice']['Service']['GreetAsync'](arg1);
}

export function SetContext(arg1) {
  return window['go']['homeservice']['Service']['SetContext'](arg1);
}
